
npm i @formatjs/intl-localematcher --save 
npm i @heroicons/react --save 
npm i @tailwindcss/typography --save 
npm i clsx --save 
npm i gray-matter --save 
npm i marked --save 
npm i mongodb --save 
npm i negotiator --save 
npm i next --save 
npm i next-i18n-router --save 
npm i react --save 
npm i react-dom --save 
npm i react-icons --save 
npm i react-intl --save 
npm i react-slick --save 
npm i sharp --save 
npm i slick-carousel --save 
npm i tailwind-merge --save 



npm i @commitlint/cli  --save-dev
npm i @commitlint/config-conventional --save-dev
npm i @svgr/webpack --save-dev
npm i @tailwindcss/forms --save-dev
npm i @testing-library/jest-dom --save-dev
npm i @testing-library/react --save-dev
npm i @types/marked --save-dev
npm i @types/react --save-dev
npm i @types/sharp --save-dev
npm i @typescript-eslint/eslint-plugin --save-dev
npm i @typescript-eslint/parser --save-dev
npm i autoprefixer --save-dev
npm i eslint --save-dev
npm i eslint-config-next --save-dev
npm i eslint-config-prettier --save-dev
npm i eslint-plugin-simple-import-sort --save-dev
npm i eslint-plugin-unused-imports --save-dev
npm i husky --save-dev
npm i jest --save-dev
npm i jest-environment-jsdom --save-dev
npm i lint-staged --save-dev
npm i next-router-mock --save-dev
npm i next-sitemap --save-dev
npm i postcss --save-dev
npm i prettier --save-dev
npm i prettier-plugin-tailwindcss --save-dev
npm i tailwindcss --save-dev
npm i typescript --save-dev
npm install @typescript-eslint/eslint-plugin@latest --save-dev